# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DVObY0LhKHp14VX0xpW2noFVbJYb29VH
"""

import argparse

parser=argparse.ArgumentParser(description='adding one integer')

parser.add_argument('n1',type=int,default=1)

args = parser.parse_args()

num = args.n1
testn = 2

while ((testn*testn)<=num):
	if (num%testn)==0:
		testn=0
		break
	testn+=1

if testn==0 or num==1:
	print(f'{num} is not a prime')
else:
	print(f'{num} is a prime')